# Generated by Django 3.0.6 on 2020-08-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200816_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=' ', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
