# Generated by Django 3.0.6 on 2020-08-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200816_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=70)),
                ('phone', models.IntegerField(blank=True, max_length=20)),
                ('desc', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
